// Generated by CoffeeScript 1.6.1
(function() {
  var Bingo,
    _this = this;

  console.log("hi");

  Bingo = (function() {

    function Bingo() {
      var _i, _results,
        _this = this;
      this.change = function() {
        return Bingo.prototype.change.apply(_this, arguments);
      };
      this.shuffle = _.shuffle((function() {
        _results = [];
        for (_i = 1; _i <= 75; _i++){ _results.push(_i); }
        return _results;
      }).apply(this));
      this.main = ko.observable(this.shuffle.shift());
      this.hist = ko.observableArray([this.main()]);
    }

    Bingo.prototype.change = function() {
      this.main(this.shuffle.shift());
      return this.hist.push(this.main());
    };

    return Bingo;

  })();

  $(function() {
    var bingo;
    bingo = new Bingo;
    return ko.applyBindings(bingo);
  });

}).call(this);
